### ISSUE TITLE
Travis CI builds failing

### ISSUE THREAD

**Issue by dalgibbard** [tradel/AppDynamicsREST#11]
Hey there;
Looks like pull requests are failing CI (#7 and #10); due to the following:

```
======================================================================
ERROR: Failure: ImportError (No module named creds.localhost)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/build/tradel/AppDynamicsREST/test/test.py", line 10, in <module>
    import creds.localhost as creds
ImportError: No module named creds.localhost
```

**Comment by tradel** [comment]
I'm sorry, I am no longer with AppDynamics, and this project is no longer being maintained. Please feel free to fork the project and work on it yourself! Thanks.

**Comment by dalgibbard** [comment]
Fair enough! Good luck with your future endeavours :)
