### ISSUE TITLE
AppDynamics Pro version compatibility?

### ISSUE THREAD

**Issue by foragerr** [tradel/AppDynamicsREST#8]
Is there a map of what AppDynamicsREST version is compatible with what AppDynamics controller version? I ran sample.py from AppDynamicsREST 0.4.5 against an on-premise AppDynamics controller version 3.9.5.2 build 11, and got this error:

```
python sample.py -c http://appdhost:8090/ -u user -p *****
APP1 0 0 0 0
APP2 2 1 0 0.0
APP3 0 0 0 0
Traceback (most recent call last):
  File "sample.py", line 19, in <module>
    art = metric_data.by_leaf_name(c.AVERAGE_RESPONSE_TIME).first_value()
  File "build\bdist.win32\egg\appd\model\metric_data.py", line 57, in first_value
  File "build\bdist.win32\egg\appd\model\metric_data.py", line 45, in __getitem__
IndexError: list index out of range
```

**Comment by foragerr** [comment]
On second thought this isn't a version problem; I guess the app after APP3 didn't have a `.first_value()`. I suppose `sample.py` should check for that before trying to access empty list.
