### ISSUE TITLE
sample.py throws IndexError if value not returned

### ISSUE THREAD

**Issue by dalgibbard** [tradel/AppDynamicsREST#9]
Looks like a few of our Application Tiers don't contain any/valid AVERAGE_RESPONSE_TIME / CALLS_PER_MINUTE etc values; which causes:

```
Traceback (most recent call last):
  File "sample.py", line 11, in <module>
    art = metric_data.by_leaf_name(c.AVERAGE_RESPONSE_TIME).first_value()
  File "build/bdist.macosx-10.10-x86_64/egg/appd/model.py", line 224, in first_value
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/UserList.py", line 31, in __getitem__
    def __getitem__(self, i): return self.data[i]
```

**Comment by tradel** [comment]
I'm sorry, I am no longer with AppDynamics, and this project is no longer being maintained. Please feel free to fork the project and work on it yourself! Thanks.
